### ISSUE TITLE
Uppercase letters

### ISSUE THREAD

**Issue by absolux** [lukeed/uid#1]
Is it possible to include uppercase letters ?

**Comment by lukeed** [comment]
Nope, lowercase only. It's intentional to avoid ambiguity within URLs

Thanks :)

**Comment by lukeed** [comment]
This also means that it's perfectly safe to cast your return-string to uppercase if you want

```js
let output = foid();

// equivalent uniqueness
output == output.toUpperCase();
```

**Comment by absolux** [comment]
> It's intentional to avoid ambiguity within URLs

if you say so. but I've made a variante of your `foid` generator.

```js
const HEX = "ZYXWVUTSRQPONMLKJIHGFEDCBAzyxwvutsrqponmlkjihgfedcba9876543210"

function foid (len) {
  var str = '', num = len || 11;
  while (num--) str += HEX[Math.random() * HEX.length | 0];
  return str;
}

// "yaQMw9lb0MX"
```
Don't worry, you still the best :wink:

**Comment by lukeed** [comment]
Haha cool, glad that works for you :)

In past experience (many times), things get lost or misidentified between services/backends because of how they handle URL segments. Some things will respect casing, some do case _insensitive_ matching, and others will auto-cast your identifiers to lowercase. IMO, it's much better to exchange some character variation for longer tokens to avoid that problem entirely.

Enjoy!

**Comment by absolux** [comment]
You're right, our past experiences influence our next moves.

Thanks for sharing.
